name: SwiftLint

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - '**/*.swift'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - name: Install Bundler
        run: gem install bundler -v 2.4.22 --user-install

      - name: Configure Bundler
        run: bundle config silence_root_warning true

      - name: Install Dependencies
        run: bundle install
        
      - name: run
        run: bundle exec danger
        
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/swift@3.18.1
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
