name: SwiftLint

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - '**/*.swift'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/swift@3.18.1
        with:
            args: --failOnErrors --no-publish-check
        env:Container action is only supported on Linux
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
