name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: '5.9'
      - name: GitHub Actions for SwiftLint
        uses: sinoru/actions-swiftlint@v6
