name: SwiftLint

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - '**/*.swift'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - name: Download SwiftLint zip
        run: wget https://github.com/realm/SwiftLint/releases/download/0.54.0/swiftlint_linux.zip
          
      - uses: actions/checkout@v1
      - run: pwd && wget https://github.com/realm/SwiftLint/releases/download/0.54.0/swiftlint_linux.zip && unzip -o swiftlint_linux.zip -d /usr/local/bin && ls
      - name: Danger
        uses: danger/swift@3.18.1
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
